version: "3"
services:
  redis:
    image: "redis:alpine"
  web:
    build:
      context: ./my_test_app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./my_test_app:/my_test_app
    ports:
     - "5000:5000"
    depends_on:
      - redis
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./my_test_app.py
      FLASK_ENV: development
  worker:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery_queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis


